#!/bin/bash
source "$(dirname "$0")/../bin/common"

echo "Removing the build directory..."
rm -rf build || { echo "Error: Could not remove [build]"; exit 1; }
echo "Successfully removed the build directory."
