ktor {
    deployment {
        port = 8080
        port = ${?SERVER_PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ com.echoapp.server.ApplicationKt.module ]
    }
}

jwt {
    secret = "local_echo_secret_key_31415"
    issuer = "http://rest-server:8080/"
    audience = "http://rest-server:8080/"
    expirationTimeMs = "36000000"
}

database {
    file = "var/echo.db"
}
